name: Setup Yarn
description: Reduce boilerplate when installing setting up Node.js and installing Yarn dependencies.
author: Mark Skelton
branding:
  icon: play
  color: blue
inputs:
  flags:
    description: Additional flags to pass to the install command.
  node-version:
    description: Node version to use, defaults to the current LTS version.
    default: "16.x"
  ref:
    description: Git ref to checkout. Passed to `actions/checkout`.
  cache:
    description: "Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm"
    default: yarn
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref }}
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.cache }}
    - name: Install dependencies
      run: yarn install --immutable ${{ inputs.flags }}
      shell: bash
